### PR TITLE
Update list of package sources

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/2085

Arcade soon will publish only to arcade-validation feed. This PR makes the eventual new packages available for arcade-validation builds.

Further details: Arcade-validation will add Arcade's build to another channel and that will cause the dotnet-core feed to be updated.

### CODE REVIEW

**Comment by JohnTortugo** [comment]
I don't have permission to set reviewers. So Cc'ing you guys here.

PTAL: @jcagme @riarenas @mmitche

**Comment by jcagme** [comment]
You have permissions now :)

**Comment by JohnTortugo** [comment]
I'm waiting for CI builds to work. Also I've a private build that isn't finishing: https://dnceng.visualstudio.com/internal/_build/results?buildId=133362

**Pull request merged**
