### PR TITLE
Made a quick script to promote assets to the Latest channel

### PR DESCRIPTION
**Pull request by missymessa**

### CODE REVIEW

**Comment by missymessa** [comment]
> Why is that needed @missymessa ?

Makes it easy for folks who aren't familiar with darc to call this cmdlet with an BAR Build ID. I could just keep the script local on my machine, but I figured it would be more useful to others if I had it in a repo for others to use.

**Comment by JohnTortugo** [comment]
> > Why is that needed @missymessa ?
> 
> Makes it easy for folks who aren't familiar with darc to call this cmdlet with an BAR Build ID. I could just keep the script local on my machine, but I figured it would be more useful to others if I had it in a repo for others to use.

Got it, thanks. The thing is that people usually pushes against having these scripts with just or a few simple commands. I think just calling Darc directly is acceptable in these cases.

/cc @chcosta

**Comment by chcosta** [comment]
I don't really see the benefit of this.  It saves a few key strokes, but only for a very targeted scenario that a very limited number of people are going to exercise and even then, they would have to know this helper script exists..  My preference is that people are forced to learn darc.

**Comment by chcosta** [comment]
I do really like the thought process here though.  You saw a gap and wrote a quick tool, then shared it with the larger group.  I think that thought process is fantastic and should be encouraged.  I just don't see a strong benefit for this particular scenario.

**Comment by missymessa** [comment]
> I don't really see the benefit of this. It saves a few key strokes, but only for a very targeted scenario that a very limited number of people are going to exercise and even then, they would have to know this helper script exists.. My preference is that people are forced to learn darc.

I'll close this and ensure that this gets added to any documentation that I write for this process.

**Pull request closed without merging**
