### PR TITLE
Add 'runtimes' to global.json for validation testing

### PR DESCRIPTION
**Pull request by natemcmaster**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Depends on https://github.com/dotnet/arcade-validation/pull/386

**Comment by natemcmaster** [comment]
cc @chcosta 

I don't have write access to this repo, but I think this would have caught issues in running dotnet-install.sh (both the chmod +x issue and  https://github.com/dotnet/arcade/issues/2730)

**Comment by chcosta** [comment]
I don't have write access either.

@ChadNedzlek @riarenas , do you know who can merge this change?

**Comment by riarenas** [comment]
Everyone in @dotnet/dnceng should now have permissions.

**Comment by riarenas** [comment]
@natemcmaster Looks like the feature is now working for Linux as well after the fixes. Thanks for adding this!

**Pull request merged**
