### PR TITLE
Make arcade-validation publish using release pipelines

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/2085

- This is for publishing packages of arcade-validation itself, not the Arcade's build validated packages
- Adjust version of SDK to latest.
- Manually import some files to `eng\common\` folder. I realize that Maestro can override these files, that's fine because the changes I'm including in this PR for those files are just verbatim copy from Arcade files.

Test build ran here: https://dnceng.visualstudio.com/internal/_build/results?buildId=128491

Publishing happened here: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=3741

### CODE REVIEW

**Comment by JohnTortugo** [comment]
I don't have permission to set reviewers.

/cc @jcagme @riarenas @mmitche

**Comment by JohnTortugo** [comment]
Looks like I hit some permission issue on the build. https://dev.azure.com/dnceng/public/_build/results?buildId=128496&view=logs&jobId=3bf40094-a109-5f90-a8f1-72c4fe3a09fd&taskId=af5be41e-cd8b-51c7-012c-a83641d723aa&lineStart=73&lineEnd=74&colStart=1&colEnd=1

Do we want to enable what's mentioned in this message: `Please Check the 'Make secrets available to builds of forks' in the pipeline pull request validation trigger settings.` ?

**Comment by jcagme** [comment]
@alexperovich @jonfortescue ?

**Comment by jonfortescue** [comment]
Yes. @alexperovich can confirm but I'm pretty positive that's what we want.

**Comment by riarenas** [comment]
I clicked the thing to enable that.

**Comment by JohnTortugo** [comment]
> I clicked the thing to enable that.

Thanks @riarenas

**Comment by riarenas** [comment]
If this version of the Helix SDK flows to repos, will their builds from forks using Helix start failing as well? Might need some communication

**Comment by jonfortescue** [comment]
@alexperovich can confirm but I think this has always been the case.

**Comment by riarenas** [comment]
> @alexperovich can confirm but I think this has always been the case.

Wouldn't that have meant that all PRs to this repo would've failed?

**Comment by jonfortescue** [comment]
ah y'all do forks a lot. Then it may be new which means you'd be correct; this would be a potentially breaking change and require upfront communication. @alexperovich

**Comment by riarenas** [comment]
Synced up, and this behavior was already communicated. We just never saw it in Arcade-Validation because of how long it had been since the last PR to the repo, and the Maestro PR updates don't use forks, but branches in the main repo.

**Pull request merged**
