### PR TITLE
Use 1ES hosted pools

### PR DESCRIPTION
**Pull request by ulisesh**
Use new Hosted Pools

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Review by adiaaida — APPROVED** [review]

**Comment by MattGal** [comment]
@ulisesh I kicked this a couple times yesterday but I don't immediately see the problem.  I almost wonder if the "The agent did not connect within the alloted time of 45 minute(s)" is load-related.

**Comment by ulisesh** [comment]
@MattGal this is blocked by https://github.com/dotnet/core-eng/issues/14359

**Comment by lpatalas** [comment]
The issue was fixed by 1ES so this is unblocked now.

**Pull request merged**
