### PR TITLE
Try SourceLink property setting

### PR DESCRIPTION
**Pull request by MattGal**
Just tossing off a PR to see if it helps with https://github.com/dotnet/arcade/issues/3069, per @adiaaida 's suggestion in the issue.

### CODE REVIEW

**Comment by adiaaida** [comment]
In order to test this, you'll also need to change https://github.com/dotnet/arcade-validation/blob/main/azure-pipelines.yml#L219 to true, and run an official ci run.

**Comment by MattGal** [comment]
> In order to test this, you'll also need to change https://github.com/dotnet/arcade-validation/blob/main/azure-pipelines.yml#L219 to true, and run an official ci run.

Thanks @adiaaida , created https://dnceng.visualstudio.com/internal/_build/results?buildId=1090759&view=results

**Review by adiaaida — COMMENTED** [review]
Looks like it worked! Let's reenable sourcelink validation for this repo in this PR, then this looks good to me

**Comment by MattGal** [comment]
@adiaaida I tried to fix the comments but the PR is wonky, going to recreate it.

**Pull request closed without merging**
